name: Release
on:
  push:
    branches:
      - main
  workflow_run:
    workflows: [tests]
    types:
      - completed
jobs:
  on-success:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Release
        uses: huggingface/semver-release-action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
